In [1]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv('customer.csv',usecols=['review','education','purchased'])

In [12]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     50 non-null     object
 1   education  50 non-null     object
 2   purchased  50 non-null     object
dtypes: object(3)
memory usage: 1.3+ KB


In [14]:
df.describe()

review education purchased
count      50        50        50
unique      3         3         2
top      Poor        PG        No
freq       18        18        26

In [16]:
x=df.iloc[: , 0:2]
y=df['purchased']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.10)

In [17]:
print(x_train)

     review education
6      Good    School
9      Good        UG
18     Good    School
26     Poor        PG
39     Poor        PG
10     Good        UG
13  Average    School
46     Poor        PG
12     Poor    School
49     Good        UG
2      Good        PG
0   Average    School
24  Average        PG
11     Good        UG
7      Poor    School
22     Poor        PG
8   Average        UG
4   Average        UG
21  Average        PG
19     Poor        PG
35     Poor    School
34  Average    School
23     Good    School
20  Average    School
5   Average    School
33     Good        PG
47     Good        PG
40     Good    School
27     Poor        PG
38     Good    School
31     Poor    School
32  Average        UG
37  Average        PG
36     Good        UG
41     Good        PG
25     Good    School
42     Good        PG
43     Poor        PG
28     Poor    School
3      Good        PG
44  Average        UG
14     Poor        PG
1      Poor        UG
30  Average        UG
29  Averag

# ordinal encoding(only input column where certain order exist)

In [18]:
df['review'].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [19]:
df['education'].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [23]:
from sklearn.preprocessing import OrdinalEncoder
#making ordinal encoder class object
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

# fit only training data
oe.fit(x_train)

# transform on both training and test data
x_train=oe.transform(x_train)
x_test=oe.transform(x_test) 

In [25]:
x_train

array([[2., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [1., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [2., 2.],
       [1., 0.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.],
       [1., 1.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [28]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [29]:
oe.get_feature_names_out

<bound method OneToOneFeatureMixin.get_feature_names_out of OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])>

# label encoding(target column always)


In [30]:
from sklearn.preprocessing import LabelEncoder
# making object
le=LabelEncoder()

#fit
le.fit(y_train)
#transform
y_train=le.transform(y_train)
y_test=le.transform(y_test)

In [31]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1])

In [32]:
y_test

array([0, 1, 1, 1, 1])

In [33]:
le.get_params

<bound method BaseEstimator.get_params of LabelEncoder()>