# creating numpy array

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a


array([1, 2, 3])

In [8]:
# 2d and 3d array
b=np.array([[1,2,3],[4,5,6]])
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [9]:
# dtypes
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [10]:
# np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [12]:
# with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [17]:
# np.ones and np.zeroes
np.ones(3)
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
# np.random
np.random.random((3,4))

array([[0.91106001, 0.02480362, 0.02824422, 0.98915483],
       [0.73121568, 0.68893671, 0.64873432, 0.44792563],
       [0.52400164, 0.1261062 , 0.35234116, 0.68622777]])

In [25]:
# np.linspace
np.linspace(-10,10,5,dtype=int)

array([-10,  -5,   0,   5,  10])

In [24]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array attribute

In [28]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [29]:
#ndim
a2.ndim

2

In [32]:
#shape
a1.shape
a2.shape
a3.shape

(2, 2, 2)

In [34]:
#size
a3.size
a2.size

12

In [35]:
#itemsize
a3.itemsize

4

In [36]:
#dtype
print(a1.dtype)

int32


# changing data type

In [40]:
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# array operations

In [41]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [42]:
# scaler operation
#arithmatic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [44]:
#relational
a2>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
#vector operation
# arithmatic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

# array functions

In [52]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[24., 52., 58.],
       [ 9., 54., 80.],
       [64.,  8.,  9.]])

In [56]:
# max,min,sum,prod
print(np.max(a1))
print(np.min(a1))
print(np.prod(a1))
print(np.sum(a1))

80.0
8.0
12968247951360.0
358.0


In [58]:
# maximum item in every row
# 0->col, 1->row
np.max(a1,axis=1)

array([58., 80., 64.])

In [64]:
# mean,median,std,var
print(np.mean(a1))
print(np.median(a1))
print(np.std(a1))
print(np.var(a1))

39.77777777777778
52.0
25.90914801025468
671.283950617284


In [65]:
#trigonometric
np.sin(a1)

array([[-0.90557836,  0.98662759,  0.99287265],
       [ 0.41211849, -0.55878905, -0.99388865],
       [ 0.92002604,  0.98935825,  0.41211849]])

In [66]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [69]:
# log and exponent
np.log(a1)
np.exp(a1)

array([[2.64891221e+10, 3.83100800e+22, 1.54553894e+25],
       [8.10308393e+03, 2.83075330e+23, 5.54062238e+34],
       [6.23514908e+27, 2.98095799e+03, 8.10308393e+03]])

In [76]:
# round , floor ,ceil
print(np.round(np.random.random((2,3))*100))
print(np.floor(np.random.random((2,3))*100))
print(np.ceil(np.random.random((2,3))*100))

[[82. 39. 81.]
 [ 3. 55. 95.]]
[[56. 78. 80.]
 [87. 68. 76.]]
[[24. 74. 84.]
 [34. 23. 11.]]


# indexing and slicing

In [79]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [80]:
a1[-1]

9

In [81]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [82]:
a2[1,2]

6

In [83]:
a3


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [84]:
a3[1,0,1]

5

In [85]:
a1[2:5]

array([2, 3, 4])

In [88]:
a2[0,:]

array([0, 1, 2, 3])

In [89]:
a2[1: ,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [90]:
a2[::2 , : :3 ]

array([[ 0,  3],
       [ 8, 11]])

# iterating